function greedy = david2_best(feasible,w)
% This function computes the codeset using two different greedy algorithms.
% Called by: main
% Calls: none
% Input variables:
% feasible: vector of indices of faithful codes
% w: length of word
% Output variable:
% greedy: two columns of codesets generated by different greedy algorithms
% Internal variables:
    esize = 2^w; % size of codebook
    greedy = zeros(esize); % Matrix of encoding set
    % feasible(end) is the largest Walsh score, so the optimal distance would
    % be this over the size of the encoding set, no matter the algorithm
    greedy(esize)=feasible(end);
    % Now do the greedy last algorithm.
    for j = esize:-1:2
        % Step 1. Set the optimum distance for what is left, using the basin
        % of attraction distance. 
        optdis = greedy(j)/(j-1/2);
        % Step 2. Filter the feasible vectors so only entries are retained
        % which are an odd distance from the set vectors. First, construct a
        % vector of 0's and 1's depending on whether the distance is odd:
        indset = mod(abs(feasible - greedy(j,2)),2)==1;
        % Then select only the entries of feasible that are spaced correctly:
        oddfeas = feasible(indset);
        % Step 3. Choose the entry that is optdis away or more. Find finds a
        % vector of all the INDICES that satsify, and then we choose the last
        % (highest) one.
        testfind = find(oddfeas <= (greedy(j)-optdis),1,'last');
        testfind = oddfeas(testfind);
        % If testfind can't find anything (probably only at the final
        % point), then we just reduce the optimal distance by 1 until we
        % get a result.
        while isempty(testfind)
            optdis = optdis - 1;
            testfind = find(oddfeas >= (greedy(j)-optdis),1,'first');
            testfind = oddfeas(testfind);
        end
    greedy(j-1) = testfind;
    end
    % Sort the columns in increasing order.
    greedy = sort(greedy);
end