function greedy = david_best(feasible,w)
% DAVID_BEST generates a codebook from given a given feasible set using two
% different algorithms. Everything below this comment block was taken
% directly from David's Github branch on 6/28/26 and has not been modified.
%
%last updated 06/28/2026 by Adam Petrucci

% This function computes the codeset using two different greedy algorithms.

% Called by: main
% Calls: none

% Input variables:
% feasible: vector of indices of faithful codes
% w: length of word

% Output variable:
% greedy: two columns of codesets generated by different greedy algorithms

% Internal variables:
% alg: 1 if greedy first, 2 if greedy last
esize = 2^w; % size of codebook
greedy = zeros(esize,2); % Matrix of encoding set
% indset: set to test for distances (indices)
% j: Loop over entry in codebook
% oddfeas: set to test for distances (entries)
% optdis: optimum distance to keep entries equally spaced
% testfind: best entry for next word in codebook
% testset: differences between codebook and last enteredd entry

% feasible(end) is the largest Walsh score, so the optimal distance would
% be this over the size of the encoding set, no matter the algorithm
greedy(esize,:)=feasible(end);

% Iterate over algorithm.

for alg = 1:2
    for j = esize:-1:2
        % Step 1.  Set the optimum distance for what is left, using the basin
        % of attraction distance.
        optdis = greedy(j,alg)/(j-1/2);
        % Step 2.  Filter the feasible vectors so only entries are retained
        % which are less than the most recent entry, and at an odd distance.
        % First we create the set to test:
        testset = feasible - greedy(j,alg);
        % Then do the check
        indset = (mod(testset,2)==1) & (testset<0);
        % Then select only the entries of feasible that are spaced correctly:
        oddfeas = feasible(indset);
        % Step 3.  This is the part that is different depending on alg.
        if alg == 1
            %If
            % alg=1, this is greedy first, so we choose the entry that is optdis away or more.
            % Find finds a
            % vector of all the INDICES that satsify, and then we choose the last
            % (highest) one.
            testfind = find(oddfeas <= (greedy(j,alg)-optdis),1,'last');
        else
            %If
            % alg=2, this is greedy lasgt, so we choose the entry that is
            % optdis away or less.  Find finds a
            % vector of all the INDICES that satisfy, and then we choose the first
            % (least) one.
            testfind = find(oddfeas >= (greedy(j,alg)-optdis),1,'first');
        end
        testfind = oddfeas(testfind);
        % If testfind can't find anything:
        while isempty(testfind)
            if alg == 1
                % If we are doing greedy first, we reduce the distance by 1,
                % then try again.
                optdis = optdis - 1;
            end
            % If we are doiung greedy last, then there isn't anything closer
            % than optdis, so for this one time we use greedy first, and only
            % reduce the distance by 1 if we still can't find anything:
            testfind = find(oddfeas <= (greedy(j,alg)-optdis),1,'last');
            testfind = oddfeas(testfind);
            if alg == 2
                optdis = optdis - 1;
            end
            % However, it is possible that we can't get a result if we have
            % gone all the way to the first entry before j=1.  In that case, we
            % just set everything equal to the previous entry, which will cause the minimum
            % distance to be 0:
            if optdis<0
                testfind = greedy(j,alg);
            end
        end
        greedy(j-1,alg) = testfind;
    end
end

% Sort the columns in increasing order.
greedy = sort(greedy);

end